# Generated by Django 6.1.1 on 2026-09-14 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_carrinho_carrinhoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoitem',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrinhas', to='loja.produto'),
        ),
    ]
